# Generated by Django 3.1 on 2021-01-08 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lstv_api_v1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='slug',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
    ]
