# Generated by Django 3.1 on 2021-01-12 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lstv_api_v1', '0002_auto_20210108_0153'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentsearchquery',
            name='placeholder',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
