# Generated by Django 3.1 on 2021-01-12 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lstv_api_v1', '0003_contentsearchquery_placeholder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentsearchquery',
            name='placeholder',
        ),
    ]
