# Generated by Django 3.1 on 2021-01-11 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lstv_api_v1', '0003_auto_20210111_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizedevent',
            name='event_end_date_time',
            field=models.DateTimeField(db_index=True, null=True),
        ),
    ]
