# Generated by Django 3.1 on 2021-01-12 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lstv_api_v1', '0004_remove_contentsearchquery_placeholder'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentsearchquery',
            name='group',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
