# Generated by Django 3.1 on 2021-01-12 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lstv_api_v1', '0006_article_associated_articles'),
        ('lstv_api_v1', '0005_contentsearchquery_group'),
    ]

    operations = [
    ]
