# Generated by Django 3.1 on 2021-01-12 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lstv_api_v1', '0008_remove_organizedevent_business'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='organized_events',
            field=models.ManyToManyField(db_table='businesses_to_organized_events', related_name='businesses', to='lstv_api_v1.OrganizedEvent'),
        ),
    ]
