# Generated by Django 3.1 on 2021-01-12 23:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lstv_api_v1', '0009_business_organized_events'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizedevent',
            name='cta_label',
        ),
        migrations.RemoveField(
            model_name='organizedevent',
            name='title',
        ),
        migrations.AddField(
            model_name='organizedevent',
            name='name',
            field=models.CharField(db_index=True, default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organizedevent',
            name='place',
            field=models.CharField(db_index=True, max_length=150, null=True),
        ),
    ]
