# Generated by Django 3.1 on 2021-01-12 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lstv_api_v1', '0010_auto_20210112_2311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizedevent',
            name='logo_image',
        ),
    ]
