# Generated by Django 3.1 on 2021-01-12 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lstv_api_v1', '0011_remove_organizedevent_logo_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organizedevent',
            old_name='place',
            new_name='name_long',
        ),
        migrations.RenameField(
            model_name='organizedevent',
            old_name='name',
            new_name='name_short',
        ),
    ]
