# Generated by Django 3.1 on 2021-01-12 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lstv_api_v1', '0014_auto_20210112_2340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organizedevent',
            old_name='lstv_event',
            new_name='is_lstv_event',
        ),
    ]
