# Generated by Django 3.1 on 2021-01-13 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lstv_api_v1', '0015_auto_20210112_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='curated_properties',
            field=models.ManyToManyField(db_table='locations_to_curated_props', related_name='locations', to='lstv_api_v1.Properties'),
        ),
        migrations.AddField(
            model_name='tagtype',
            name='curated_properties',
            field=models.ManyToManyField(db_table='tag_types_to_curated_props', related_name='tag_types', to='lstv_api_v1.Properties'),
        ),
    ]
