# Generated by Django 3.1 on 2021-01-13 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lstv_api_v1', '0016_auto_20210113_1854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='curated_properties',
        ),
    ]
