# Generated by Django 3.1 on 2021-01-13 19:03

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import enumchoicefield.fields
import lstv_api_v1.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('lstv_api_v1', '0017_remove_location_curated_properties'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuratedLocation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('state', enumchoicefield.fields.EnumChoiceField(db_index=True, default=lstv_api_v1.models.ContentModelState(1), enum_class=lstv_api_v1.models.ContentModelState, max_length=16)),
                ('state_desc', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(db_index=True, max_length=200, null=True), null=True, size=None)),
                ('source', enumchoicefield.fields.EnumChoiceField(db_index=True, default=lstv_api_v1.models.ContentModelSource(1), enum_class=lstv_api_v1.models.ContentModelSource, max_length=7)),
                ('source_desc', models.TextField(db_index=True, max_length=100, null=True)),
                ('delete_token', models.TextField(db_index=True, max_length=15, null=True)),
                ('deleted_at', models.DateTimeField(db_index=True, null=True)),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='lstv_api_v1.country')),
                ('county', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='lstv_api_v1.county')),
                ('curated_fields', models.ManyToManyField(db_table='curated_locations_to_properties', related_name='curated_locations', to='lstv_api_v1.Properties')),
                ('place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='lstv_api_v1.place')),
                ('state_province', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='lstv_api_v1.stateprovince')),
            ],
            options={
                'db_table': 'curated_locations',
            },
        ),
    ]
