# Generated by Django 3.1 on 2021-01-13 22:47

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lstv_api_v1', '0018_curatedlocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='alt_slugs',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(db_index=True, max_length=45, null=True), db_index=True, null=True, size=None),
        ),
    ]
