# Generated by Django 3.1 on 2021-01-14 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lstv_api_v1', '0019_place_alt_slugs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='alt_slugs',
        ),
    ]
