# Generated by Django 3.1 on 2021-01-14 01:27

from django.db import migrations, models
import enumchoicefield.fields
import lstv_api_v1.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('lstv_api_v1', '0023_auto_20210114_0120'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceAltName',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('type', enumchoicefield.fields.EnumChoiceField(db_index=True, default=lstv_api_v1.models.PlaceType(1), enum_class=lstv_api_v1.models.PlaceType, max_length=8)),
                ('value', models.CharField(db_index=True, max_length=100)),
            ],
            options={
                'db_table': 'geo_place_alt_names',
            },
        ),
        migrations.AddField(
            model_name='place',
            name='alt_slugs',
            field=models.ManyToManyField(db_table='geo_places_to_alt_names', related_name='places', to='lstv_api_v1.PlaceAltName'),
        ),
    ]
