# Generated by Django 3.1 on 2021-01-14 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lstv_api_v1', '0025_auto_20210114_0130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='alt_slugs',
            new_name='alternates',
        ),
    ]
