# Generated by Django 3.1 on 2021-01-14 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lstv_api_v1', '0027_auto_20210114_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagtype',
            name='weight_businesses',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
