# Generated by Django 3.1 on 2021-01-14 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lstv_api_v1', '0028_tagtype_weight_businesses'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagtype',
            name='weight_photos',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
