# Generated by Django 3.1 on 2021-01-19 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lstv_api_v1', '0029_tagtype_weight_photos'),
        ('lstv_api_v1', '0016_auto_20210118_1840'),
    ]

    operations = [
    ]
