# Generated by Django 3.1 on 2021-01-19 14:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lstv_api_v1', '0030_merge_20210119_0432'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagtype',
            name='subscribers',
            field=models.ManyToManyField(db_table='tag_types_to_subscribers', related_name='tag_types_subscribed_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
