# Generated by Django 3.1 on 2021-01-19 23:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lstv_api_v1', '0031_tagtype_subscribers'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='subscribers',
            field=models.ManyToManyField(db_table='countries_to_subscribers', related_name='countries_subscribed_to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='county',
            name='subscribers',
            field=models.ManyToManyField(db_table='county_to_subscribers', related_name='counties_subscribed_to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='place',
            name='subscribers',
            field=models.ManyToManyField(db_table='place_to_subscribers', related_name='places_subscribed_to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stateprovince',
            name='subscribers',
            field=models.ManyToManyField(db_table='state_provinces_to_subscribers', related_name='state_province_subscribed_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
