# Generated by Django 3.1 on 2021-01-20 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lstv_api_v1', '0032_auto_20210119_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='photo_credit',
            field=models.CharField(db_index=True, max_length=50, null=True),
        ),
    ]
