# Generated by Django 3.1 on 2021-01-21 20:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lstv_api_v1', '0033_photo_photo_credit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingitem',
            name='old_price_cents',
        ),
        migrations.RemoveField(
            model_name='shoppingitem',
            name='price_cents',
        ),
        migrations.AddField(
            model_name='shoppingitem',
            name='old_price',
            field=models.CharField(db_index=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='shoppingitem',
            name='price',
            field=models.CharField(db_index=True, default="", max_length=20),
            preserve_default=False,
        ),
    ]
