# Generated by Django 3.1 on 2021-01-21 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lstv_api_v1', '0034_auto_20210121_2003'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=50, null=True)),
                ('description', models.CharField(db_index=True, max_length=200, null=True)),
                ('cta_url', models.CharField(db_index=True, max_length=150, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lstv_api_v1.business')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lstv_api_v1.photo')),
            ],
            options={
                'db_table': 'business_photos',
            },
        ),
    ]
