# Generated by Django 3.1 on 2021-01-21 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lstv_api_v1', '0035_businessphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='business_photos',
            field=models.ManyToManyField(related_name='located_business', through='lstv_api_v1.BusinessPhoto', to='lstv_api_v1.Photo'),
        ),
    ]
