# Generated by Django 3.1 on 2021-01-22 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lstv_api_v1', '0037_auto_20210121_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessphoto',
            name='order',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='businessphoto',
            name='scope',
            field=models.CharField(default='general', max_length=20),
        ),
        migrations.AddField(
            model_name='videophoto',
            name='scope',
            field=models.CharField(default='general', max_length=20),
        ),
    ]
