# Generated by Django 3.1 on 2021-01-22 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lstv_api_v1', '0038_auto_20210122_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessphoto',
            name='scope',
            field=models.CharField(default='general', max_length=50),
        ),
        migrations.AlterField(
            model_name='videophoto',
            name='scope',
            field=models.CharField(default='general', max_length=50),
        ),
    ]
