# Generated by Django 3.1 on 2021-01-22 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lstv_api_v1', '0039_auto_20210122_0010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='photo_credit_or_desc',
        ),
        migrations.AddField(
            model_name='photo',
            name='credit',
            field=models.CharField(db_index=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='description',
            field=models.CharField(db_index=True, max_length=150, null=True),
        ),
    ]
