# Generated by Django 3.1 on 2021-01-22 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lstv_api_v1', '0041_organizedevent_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='business_photos',
            field=models.ManyToManyField(related_name='photo_owning_business', through='lstv_api_v1.BusinessPhoto', to='lstv_api_v1.Photo'),
        ),
    ]
