# Generated by Django 3.1 on 2021-01-22 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lstv_api_v1', '0044_shoppingitem_thumbnail_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='shopping_items',
            field=models.ManyToManyField(db_table='businesses_to_shopping_items', related_name='businesses', to='lstv_api_v1.ShoppingItem'),
        ),
    ]
