# Generated by Django 3.1 on 2021-01-22 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lstv_api_v1', '0046_auto_20210122_2052'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(db_index=True, default=0)),
                ('title', models.CharField(db_index=True, max_length=150, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lstv_api_v1.business')),
                ('video_source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lstv_api_v1.videosource')),
            ],
            options={
                'db_table': 'promo_videos',
                'ordering': ['order'],
            },
        ),
    ]
