# Generated by Django 3.1 on 2021-01-22 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lstv_api_v1', '0047_promovideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='promo_videos',
            field=models.ManyToManyField(related_name='businesses', through='lstv_api_v1.PromoVideo', to='lstv_api_v1.VideoSource'),
        ),
    ]
