# Generated by Django 3.1 on 2021-01-25 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lstv_api_v1', '0049_auto_20210125_1653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizedevent',
            name='event_end_date_time',
        ),
        migrations.RemoveField(
            model_name='organizedevent',
            name='event_start_date_time',
        ),
    ]
