# Generated by Django 3.1 on 2021-01-26 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lstv_api_v1', '0050_auto_20210125_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='organized_events',
            field=models.ManyToManyField(db_table='businesses_to_organized_events', related_name='event_businesses', to='lstv_api_v1.OrganizedEvent'),
        ),
    ]
