# Generated by Django 3.1 on 2021-01-27 22:18

from django.db import migrations, models
import enumchoicefield.fields
import lstv_api_v1.models


class Migration(migrations.Migration):

    dependencies = [
        ('lstv_api_v1', '0051_auto_20210126_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='sold_at_businesses',
            field=models.ManyToManyField(db_table='businesses_to_sold_at_businesses', related_name='businesses_selling', to='lstv_api_v1.Business'),
        ),
        migrations.AlterField(
            model_name='contentsearchquery',
            name='content_search_type',
            field=enumchoicefield.fields.EnumChoiceField(db_index=True, enum_class=lstv_api_v1.models.ContentSearchQuerySourcingType, max_length=30),
        ),
    ]
