# Generated by Django 3.1 on 2021-01-27 22:30

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lstv_api_v1', '0052_auto_20210127_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentsearchquery',
            name='limit_to_business_roles',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(db_index=True, max_length=150, null=True), null=True, size=None),
        ),
    ]
