# Generated by Django 3.1 on 2021-01-27 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lstv_api_v1', '0053_contentsearchquery_limit_to_business_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentsearchquery',
            name='initial_num_cards_mobile',
        ),
        migrations.RemoveField(
            model_name='contentsearchquery',
            name='initial_num_cards_tablet',
        ),
        migrations.RemoveField(
            model_name='contentsearchquery',
            name='more_num_cards_desktop',
        ),
        migrations.RemoveField(
            model_name='contentsearchquery',
            name='more_num_cards_mobile',
        ),
        migrations.RemoveField(
            model_name='contentsearchquery',
            name='more_num_cards_tablet',
        ),
    ]
