# Generated by Django 3.1 on 2021-01-27 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lstv_api_v1', '0054_auto_20210127_2304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentsearchquery',
            name='initial_num_cards_desktop',
        ),
    ]
