# Generated by Django 3.1 on 2021-01-29 01:09

from django.db import migrations
import enumchoicefield.fields
import lstv_api_v1.models


class Migration(migrations.Migration):

    dependencies = [
        ('lstv_api_v1', '0056_contentsearchquery_verbosity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentsearchquery',
            name='content_sort_method',
            field=enumchoicefield.fields.EnumChoiceField(db_index=True, enum_class=lstv_api_v1.models.ContentSearchQueryOrderType, max_length=21),
        ),
    ]
