# Generated by Django 3.1 on 2021-01-29 18:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lstv_api_v1', '0059_auto_20210129_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentsearchquery',
            name='limit_to_location',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(db_index=True, max_length=500, null=True), null=True, size=None),
        ),
    ]
