# Generated by Django 3.1 on 2021-01-29 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lstv_api_v1', '0061_auto_20210129_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentsearchquery',
            name='business_location_scope',
            field=models.CharField(db_index=True, max_length=20, null=True),
        ),
    ]
