# Generated by Django 3.1 on 2021-01-30 02:17

import django.contrib.postgres.fields
from django.db import migrations, models
import enumchoicefield.fields
import lstv_api_v1.models


class Migration(migrations.Migration):

    dependencies = [
        ('lstv_api_v1', '0065_auto_20210130_0114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tagfamilytype',
            name='exclude_from_awards_display',
        ),
        migrations.AddField(
            model_name='contentsearchquery',
            name='limit_to_business_role_capacity',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(db_index=True, max_length=150, null=True), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='tagfamilytype',
            name='tag_group',
            field=enumchoicefield.fields.EnumChoiceField(db_index=True, default=lstv_api_v1.models.TagFamilyGroupType(2), enum_class=lstv_api_v1.models.TagFamilyGroupType, max_length=12),
        ),
    ]
