# Generated by Django 3.1 on 2021-01-30 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lstv_api_v1', '0066_auto_20210130_0217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businessroletype',
            old_name='name_is',
            new_name='noun',
        ),
    ]
