# Generated by Django 3.1 on 2021-01-30 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lstv_api_v1', '0067_auto_20210130_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessroletype',
            name='plural',
            field=models.CharField(db_index=True, max_length=100, null=True),
        ),
    ]
