# Generated by Django 3.1 on 2021-01-30 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lstv_api_v1', '0068_businessroletype_plural'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businessroletype',
            old_name='noun',
            new_name='singular',
        ),
    ]
