# Generated by Django 3.1 on 2021-01-30 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lstv_api_v1', '0069_auto_20210130_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='videobusinesscapacitytype',
            name='plural',
            field=models.CharField(db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='videobusinesscapacitytype',
            name='singular',
            field=models.CharField(db_index=True, max_length=100, null=True),
        ),
    ]
