# Generated by Django 3.1 on 2021-02-01 19:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('lstv_api_v1', '0071_contentsearchquery_limit_to_business'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessRoleQuickdialType',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('slug', models.CharField(db_index=True, max_length=100)),
                ('priority', models.IntegerField(db_index=True, default=0)),
                ('role_capacity_types', models.ManyToManyField(db_table='business_role_quickdial_to__role_capacity_types', related_name='role_capacity_quickdial', to='lstv_api_v1.VideoBusinessCapacityType')),
                ('role_types', models.ManyToManyField(db_table='business_role_quickdial_to__role_types', related_name='role_type_quickdial', to='lstv_api_v1.BusinessRoleType')),
            ],
            options={
                'db_table': 'business_role_quickdial',
                'ordering': ['-priority'],
            },
        ),
    ]
