# Generated by Django 3.1 on 2021-02-02 01:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('lstv_api_v1', '0076_auto_20210202_0042'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessSubscriptionLevel',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('slug', models.CharField(db_index=True, max_length=100, unique=True)),
            ],
            options={
                'db_table': 'business_subscription_levels',
            },
        ),
        migrations.AddField(
            model_name='business',
            name='subscription_level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='lstv_api_v1.businesssubscriptionlevel'),
        ),
    ]
