# Generated by Django 3.1 on 2021-02-02 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lstv_api_v1', '0077_auto_20210202_0101'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesssubscriptionlevel',
            name='numerical_value',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
