# Generated by Django 3.1 on 2021-02-03 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lstv_api_v1', '0078_businesssubscriptionlevel_numerical_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagtype',
            name='legacy_url',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
