# Generated by Django 3.1 on 2021-02-04 23:38

import django.contrib.postgres.fields
from django.db import migrations, models
import enumchoicefield.fields
import lstv_api_v1.models


class Migration(migrations.Migration):

    dependencies = [
        ('lstv_api_v1', '0079_auto_20210203_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagtype',
            name='delete_token',
            field=models.TextField(db_index=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='tagtype',
            name='deleted_at',
            field=models.DateTimeField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='tagtype',
            name='source',
            field=enumchoicefield.fields.EnumChoiceField(db_index=True, default=lstv_api_v1.models.ContentModelSource(1), enum_class=lstv_api_v1.models.ContentModelSource, max_length=7),
        ),
        migrations.AddField(
            model_name='tagtype',
            name='source_desc',
            field=models.TextField(db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tagtype',
            name='state',
            field=enumchoicefield.fields.EnumChoiceField(db_index=True, default=lstv_api_v1.models.ContentModelState(1), enum_class=lstv_api_v1.models.ContentModelState, max_length=16),
        ),
        migrations.AddField(
            model_name='tagtype',
            name='state_desc',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(db_index=True, max_length=200, null=True), null=True, size=None),
        ),
    ]
