# Generated by Django 3.1 on 2021-02-05 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lstv_api_v1', '0080_auto_20210204_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='card_thumbnail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='business_with_card_thumbnail', to='lstv_api_v1.image'),
        ),
    ]
