# Generated by Django 3.1 on 2021-02-11 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lstv_api_v1', '0082_auto_20210208_2349'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessrolefamilytype',
            name='bg_color',
            field=models.CharField(db_index=True, default='#000000', max_length=10),
            preserve_default=False,
        ),
    ]
