# Generated by Django 3.1 on 2021-02-11 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lstv_api_v1', '0083_businessrolefamilytype_bg_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='directorytype',
            name='bg_color',
            field=models.CharField(db_index=True, default='#000000', max_length=10),
            preserve_default=False,
        ),
    ]
