# Generated by Django 3.1 on 2021-02-11 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lstv_api_v1', '0084_directorytype_bg_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='directorytype',
            name='show_search',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
