# Generated by Django 3.1 on 2021-02-11 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lstv_api_v1', '0085_directorytype_show_search'),
    ]

    operations = [
        migrations.AddField(
            model_name='directorytype',
            name='description',
            field=models.TextField(db_index=True, null=True),
        ),
    ]
