# Generated by Django 3.1 on 2021-02-17 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lstv_api_v1', '0087_auto_20210217_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='opt_in_for_paid_partners',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='video',
            name='opt_in_for_social',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
