# Generated by Django 3.1 on 2021-02-17 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lstv_api_v1', '0088_auto_20210217_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='directorytype',
            name='subtitle_name_plural',
            field=models.CharField(db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='directorytype',
            name='subtitle_name_singular',
            field=models.CharField(db_index=True, max_length=100, null=True),
        ),
    ]
