# Generated by Django 3.1 on 2021-03-01 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lstv_api_v1', '0089_auto_20210217_1725'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videoplaybacklog',
            options={'select_on_save': True},
        ),
    ]
