# Generated by Django 3.1 on 2021-03-03 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lstv_api_v1', '0090_auto_20210301_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='alt_contact_cta_label',
            field=models.CharField(db_index=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='alt_contact_cta_link',
            field=models.CharField(db_index=True, max_length=150, null=True),
        ),
    ]
