# Generated by Django 3.1 on 2021-03-03 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lstv_api_v1', '0091_auto_20210303_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='inquiry_email',
            field=models.CharField(db_index=True, max_length=150, null=True),
        ),
    ]
