# Generated by Django 3.1 on 2021-03-05 19:32

from django.db import migrations
import enumchoicefield.fields
import lstv_api_v1.models


class Migration(migrations.Migration):

    dependencies = [
        ('lstv_api_v1', '0094_auto_20210303_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='visibility',
            field=enumchoicefield.fields.EnumChoiceField(db_index=True, default=lstv_api_v1.models.PostVisibilityEnum(3), enum_class=lstv_api_v1.models.PostVisibilityEnum, max_length=16),
        ),
        migrations.AlterField(
            model_name='video',
            name='visibility',
            field=enumchoicefield.fields.EnumChoiceField(db_index=True, default=lstv_api_v1.models.PostVisibilityEnum(3), enum_class=lstv_api_v1.models.PostVisibilityEnum, max_length=16),
        ),
    ]
