# Generated by Django 3.1 on 2021-03-17 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lstv_api_v1', '0095_auto_20210305_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directorytype',
            name='role_types',
            field=models.ManyToManyField(db_table='directories_to_role_types', related_name='directories_to_role_types', to='lstv_api_v1.BusinessRoleType'),
        ),
    ]
