# Generated by Django 3.1 on 2021-03-17 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lstv_api_v1', '0097_auto_20210316_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='state_reason',
            field=models.TextField(db_index=True, null=True),
        ),
    ]
