# Generated by Django 3.1 on 2021-03-18 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lstv_api_v1', '0099_auto_20210317_2134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='directorytype',
            name='show_search',
        ),
        migrations.AddField(
            model_name='directorytype',
            name='show_in_search',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
