# Generated by Django 3.1 on 2021-03-18 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lstv_api_v1', '0100_auto_20210318_2124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='directorytype',
            name='show_in_search',
        ),
        migrations.AddField(
            model_name='directorytype',
            name='show_in_search_roles',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='directorytype',
            name='show_search',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
