# Generated by Django 3.1 on 2021-03-18 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lstv_api_v1', '0101_auto_20210318_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directorytype',
            name='show_in_search_roles',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
