# Generated by Django 3.1 on 2021-03-23 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lstv_api_v1', '0102_auto_20210318_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessroletype',
            name='bg_color',
            field=models.CharField(db_index=True, max_length=10, null=True),
        ),
    ]
