# Generated by Django 3.1 on 2021-03-25 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lstv_api_v1', '0103_businessroletype_bg_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='directorytype',
            name='description_location',
            field=models.TextField(db_index=True, null=True),
        ),
    ]
