# Generated by Django 3.1 on 2021-03-29 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lstv_api_v1', '0104_directorytype_description_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='account_claim_link',
            field=models.CharField(db_index=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='account_claimed_at',
            field=models.DateTimeField(db_index=True, null=True),
        ),
    ]
