# Generated by Django 3.1 on 2021-03-29 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lstv_api_v1', '0105_auto_20210329_1558'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='account_claim_link',
            new_name='account_claim_code',
        ),
    ]
