# Generated by Django 3.1 on 2021-04-02 03:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lstv_api_v1', '0107_business_account_claim_code_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessteammember',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='team_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
