# Generated by Django 3.1 on 2021-04-02 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lstv_api_v1', '0108_auto_20210402_0353'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ip_addresses',
            field=models.ManyToManyField(db_table='users_to_ip_addresses', related_name='ip_user', to='lstv_api_v1.IPAddress'),
        ),
    ]
