# Generated by Django 3.1 on 2021-04-05 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lstv_api_v1', '0096_auto_20210317_0214'),
        ('lstv_api_v1', '0109_user_ip_addresses'),
    ]

    operations = [
    ]
