# Generated by Django 3.1 on 2021-04-09 15:06

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lstv_api_v1', '0112_auto_20210407_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentsearchquery',
            name='exclude_business_roles',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(db_index=True, max_length=150, null=True), null=True, size=None),
        ),
    ]
