# Generated by Django 3.1 on 2021-04-21 03:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lstv_api_v1', '0113_contentsearchquery_exclude_business_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoVideoViewLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('unique_guest_uuid', models.UUIDField(db_index=True, null=True)),
                ('migrated_to_log_cluster', models.BooleanField(db_index=True, default=False)),
                ('legacy_post_id', models.IntegerField(db_index=True, null=True)),
                ('legacy_user_id', models.IntegerField(db_index=True, null=True)),
                ('ip', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='lstv_api_v1.ipaddress')),
                ('promo_video', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promo_video_view_logs', related_query_name='promo_video_views_logs', to='lstv_api_v1.promovideo')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promo_video_view_logs', related_query_name='promo_video_view_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'promo_video_view_log',
            },
        ),
    ]
