# Generated by Django 3.1 on 2021-04-21 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lstv_api_v1', '0114_promovideoviewlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promovideoviewlog',
            name='promo_video',
        ),
        migrations.AddField(
            model_name='promovideoviewlog',
            name='video_source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promo_video_view_logs', related_query_name='promo_video_views_logs', to='lstv_api_v1.videosource'),
        ),
    ]
