# Generated by Django 3.1 on 2021-04-28 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lstv_api_v1', '0115_auto_20210421_0408'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='hide_email',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
