# Generated by Django 3.1 on 2021-04-26 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lstv_api_v1', '0116_auto_20210426_0259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessweightedworklocationhistory',
            name='first_recorded_work',
        ),
        migrations.RemoveField(
            model_name='businessweightedworklocationhistory',
            name='latest_recorded_work',
        ),
    ]
