# Generated by Django 3.1 on 2021-04-28 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lstv_api_v1', '0117_auto_20210426_0439'),
        ('lstv_api_v1', '0116_business_hide_email'),
    ]

    operations = [
    ]
