# Generated by Django 3.1 on 2021-04-26 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lstv_api_v1', '0117_auto_20210426_0439'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='suggested_email',
            field=models.CharField(db_index=True, max_length=150, null=True),
        ),
    ]
