# Generated by Django 3.1 on 2021-04-27 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lstv_api_v1', '0118_business_suggested_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='videosource',
            name='upload_token',
            field=models.CharField(db_index=True, max_length=25, null=True),
        ),
    ]
