# Generated by Django 3.1 on 2021-04-27 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lstv_api_v1', '0119_videosource_upload_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='suggested_role_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='suggested_businesses', to='lstv_api_v1.businessroletype'),
        ),
    ]
