# Generated by Django 3.1 on 2021-04-27 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lstv_api_v1', '0120_business_suggested_role_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videosource',
            name='media_id',
            field=models.CharField(db_index=True, max_length=50, null=True),
        ),
    ]
