# Generated by Django 3.1 on 2021-04-27 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lstv_api_v1', '0122_video_draft'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='draft',
            new_name='is_draft',
        ),
    ]
