# Generated by Django 3.1 on 2021-04-27 23:12

from django.db import migrations
import enumchoicefield.fields
import lstv_api_v1.models


class Migration(migrations.Migration):

    dependencies = [
        ('lstv_api_v1', '0123_auto_20210427_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentsearchquery',
            name='verbosity',
            field=enumchoicefield.fields.EnumChoiceField(db_index=True, default=lstv_api_v1.models.ContentVerbosityType(1), enum_class=lstv_api_v1.models.ContentVerbosityType, max_length=19),
        ),
    ]
