# Generated by Django 3.1 on 2021-04-28 00:00

from django.db import migrations
import enumchoicefield.fields
import lstv_api_v1.models


class Migration(migrations.Migration):

    dependencies = [
        ('lstv_api_v1', '0126_promovideo_is_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='promovideo',
            name='visibility',
            field=enumchoicefield.fields.EnumChoiceField(db_index=True, default=lstv_api_v1.models.PostVisibilityEnum(3), enum_class=lstv_api_v1.models.PostVisibilityEnum, max_length=16),
        ),
    ]
