# Generated by Django 3.1 on 2021-04-28 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lstv_api_v1', '0127_promovideo_visibility'),
        ('lstv_api_v1', '0118_merge_20210428_0311'),
    ]

    operations = [
    ]
