# Generated by Django 3.1 on 2021-04-30 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lstv_api_v1', '0130_auto_20210429_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagtype',
            name='suggested_by_business',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tag_suggesting_business', to='lstv_api_v1.business'),
        ),
    ]
