# Generated by Django 3.1 on 2021-05-07 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lstv_api_v1', '0131_auto_20210430_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='promovideo',
            name='opt_in_for_social_and_paid',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
