# Generated by Django 3.1 on 2021-05-07 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lstv_api_v1', '0131_auto_20210430_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentsearchquery',
            name='cta_url',
            field=models.CharField(db_index=True, default='', max_length=150),
            preserve_default=False,
        ),
    ]
