# Generated by Django 3.1 on 2021-05-04 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lstv_api_v1', '0131_auto_20210430_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='from_first_name',
            field=models.CharField(db_index=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='from_last_name',
            field=models.CharField(db_index=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='from_profile_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='lstv_api_v1.image'),
        ),
    ]
