# Generated by Django 3.1 on 2021-05-07 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lstv_api_v1', '0132_add_from_fields_to_review'),
        ('lstv_api_v1', '0132_promovideo_opt_in_for_social_and_paid'),
    ]

    operations = [
    ]
