# Generated by Django 3.1 on 2021-05-07 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lstv_api_v1', '0133_merge_20210507_1535'),
        ('lstv_api_v1', '0132_auto_20210507_1733'),
    ]

    operations = [
    ]
