# Generated by Django 3.1 on 2021-05-13 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lstv_api_v1', '0133_add_long_lat_to_geo_models'),
        ('lstv_api_v1', '0134_merge_20210507_1757'),
    ]

    operations = [
    ]
