# Generated by Django 3.1 on 2021-05-11 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lstv_api_v1', '0134_merge_20210507_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content_md',
            field=models.TextField(null=True),
        ),
    ]
