# Generated by Django 3.1 on 2021-05-17 16:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lstv_api_v1', '0135_merge_20210513_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='associated_articles',
            field=models.ManyToManyField(db_table='v1_articles_to_associated_articles', related_name='_article_associated_articles_+', to='lstv_api_v1.Article'),
        ),
        migrations.AlterField(
            model_name='article',
            name='businesses',
            field=models.ManyToManyField(db_table='v1_articles_to_businesses', related_name='articles', to='lstv_api_v1.Business'),
        ),
        migrations.AlterField(
            model_name='article',
            name='locations',
            field=models.ManyToManyField(db_table='v1_articles_to_locations', related_name='articles', to='lstv_api_v1.Location'),
        ),
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(db_table='v1_articles_to_vibe_types', related_name='articles', to='lstv_api_v1.TagType'),
        ),
        migrations.AlterField(
            model_name='business',
            name='associate_brands',
            field=models.ManyToManyField(db_table='v1_businesses_to_associate_brands', related_name='businesses', to='lstv_api_v1.Brand'),
        ),
        migrations.AlterField(
            model_name='business',
            name='business_phones',
            field=models.ManyToManyField(db_table='v1_businesses_to_business_phones', related_name='businesses', to='lstv_api_v1.Phone'),
        ),
        migrations.AlterField(
            model_name='business',
            name='coverage_locations',
            field=models.ManyToManyField(db_table='v1_businesses_to_coverage_locations', related_name='works_at_business', to='lstv_api_v1.Location'),
        ),
        migrations.AlterField(
            model_name='business',
            name='faq',
            field=models.ManyToManyField(db_table='v1_business_to_faq', related_name='faq_businesses', to='lstv_api_v1.Message'),
        ),
        migrations.AlterField(
            model_name='business',
            name='groups',
            field=models.ManyToManyField(db_table='v1_businesses_to_business_groups', related_name='group_business', to='lstv_api_v1.BusinessGroupType'),
        ),
        migrations.AlterField(
            model_name='business',
            name='organized_events',
            field=models.ManyToManyField(db_table='v1_businesses_to_organized_events', related_name='event_businesses', to='lstv_api_v1.OrganizedEvent'),
        ),
        migrations.AlterField(
            model_name='business',
            name='properties',
            field=models.ManyToManyField(db_table='v1_businesses_to_properties', related_name='businesses', to='lstv_api_v1.Properties'),
        ),
        migrations.AlterField(
            model_name='business',
            name='public_team',
            field=models.ManyToManyField(db_table='v1_business_to_public_personnel', related_name='public_personnel_businesses', to='lstv_api_v1.PublicTeamPerson'),
        ),
        migrations.AlterField(
            model_name='business',
            name='public_team_faq',
            field=models.ManyToManyField(db_table='v1_business_to_team_faq', related_name='businesses_for_team_faq', to='lstv_api_v1.Message'),
        ),
        migrations.AlterField(
            model_name='business',
            name='reviews',
            field=models.ManyToManyField(db_table='v1_business_to_reviews', related_name='business_in_review', to='lstv_api_v1.Review'),
        ),
        migrations.AlterField(
            model_name='business',
            name='roles',
            field=models.ManyToManyField(db_table='v1_business_to_role_types', related_name='business_roles', to='lstv_api_v1.BusinessRoleType'),
        ),
        migrations.AlterField(
            model_name='business',
            name='shopping_items',
            field=models.ManyToManyField(db_table='v1_businesses_to_shopping_items', related_name='businesses', to='lstv_api_v1.ShoppingItem'),
        ),
        migrations.AlterField(
            model_name='business',
            name='social_links',
            field=models.ManyToManyField(db_table='v1_businesses_to_social_network_links', related_name='social_network_businesses', to='lstv_api_v1.SocialLink'),
        ),
        migrations.AlterField(
            model_name='business',
            name='sold_at_businesses',
            field=models.ManyToManyField(db_table='v1_businesses_to_sold_at_businesses', related_name='businesses_selling', to='lstv_api_v1.Business'),
        ),
        migrations.AlterField(
            model_name='business',
            name='subscribers',
            field=models.ManyToManyField(db_table='v1_businesses_to_subscribers', related_name='businesses_subscribed_to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='business',
            name='tags',
            field=models.ManyToManyField(db_table='v1_businesses_to_tag_types', related_name='businesses', to='lstv_api_v1.TagType'),
        ),
        migrations.AlterField(
            model_name='business',
            name='worked_at_cache',
            field=models.ManyToManyField(db_table='v1_businesses_to_weighted_work_location_history', related_name='business_who_worked_there', to='lstv_api_v1.BusinessWeightedWorkLocationHistory'),
        ),
        migrations.AlterField(
            model_name='businessteammember',
            name='roles',
            field=models.ManyToManyField(db_table='v1_business_team_members_to_team_member_role_types', related_name='business_team_members', to='lstv_api_v1.BusinessTeamMemberRoleType'),
        ),
        migrations.AlterField(
            model_name='businessteammemberroletype',
            name='permissions',
            field=models.ManyToManyField(db_table='v1_business_team_member_role_types_to_role_permission_types', related_name='business_team_member_role_types_to_role_permission_types', to='lstv_api_v1.BusinessTeamMemberRolePermissionType'),
        ),
        migrations.AlterField(
            model_name='compositecontentbinding',
            name='composite_content_elements',
            field=models.ManyToManyField(db_table='v1_composite_content_bindings_to_elements', related_name='composite_content_bindings', to='lstv_api_v1.CompositeContentBindingItem'),
        ),
        migrations.AlterField(
            model_name='country',
            name='subscribers',
            field=models.ManyToManyField(db_table='v1_countries_to_subscribers', related_name='countries_subscribed_to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='county',
            name='subscribers',
            field=models.ManyToManyField(db_table='v1_county_to_subscribers', related_name='counties_subscribed_to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='curatedlocation',
            name='curated_fields',
            field=models.ManyToManyField(db_table='v1_curated_locations_to_properties', related_name='curated_locations', to='lstv_api_v1.Properties'),
        ),
        migrations.AlterField(
            model_name='directorytype',
            name='role_capacity_types',
            field=models.ManyToManyField(db_table='v1_directories_to_role_capacity_types', related_name='role_capacity_types_directory', to='lstv_api_v1.VideoBusinessCapacityType'),
        ),
        migrations.AlterField(
            model_name='directorytype',
            name='role_types',
            field=models.ManyToManyField(db_table='v1_directories_to_role_types', related_name='related_directory', to='lstv_api_v1.BusinessRoleType'),
        ),
        migrations.AlterField(
            model_name='discover',
            name='properties',
            field=models.ManyToManyField(db_table='v1_discover_to_properties', related_name='discover', to='lstv_api_v1.Properties'),
        ),
        migrations.AlterField(
            model_name='interviewpagetype',
            name='questions',
            field=models.ManyToManyField(db_table='v1_interview_page_type_to_questions', related_name='interview_page_type', to='lstv_api_v1.InterviewPropertyType'),
        ),
        migrations.AlterField(
            model_name='interviewtype',
            name='interview_pages',
            field=models.ManyToManyField(db_table='v1_interview_type_to_pages', related_name='interview_type', to='lstv_api_v1.InterviewPageType'),
        ),
        migrations.AlterField(
            model_name='message',
            name='flags',
            field=models.ManyToManyField(db_table='v1_messages_to_flags', related_name='messages', to='lstv_api_v1.ContentFlag'),
        ),
        migrations.AlterField(
            model_name='place',
            name='alternates',
            field=models.ManyToManyField(db_table='v1_geo_places_to_alt_names', related_name='places', to='lstv_api_v1.PlaceAltName'),
        ),
        migrations.AlterField(
            model_name='place',
            name='subscribers',
            field=models.ManyToManyField(db_table='v1_place_to_subscribers', related_name='places_subscribed_to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='editors',
            field=models.ManyToManyField(db_table='v1_posts_to_editors', related_name='editable_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='properties',
            field=models.ManyToManyField(db_table='v1_posts_to_properties', related_name='posts', to='lstv_api_v1.Properties'),
        ),
        migrations.AlterField(
            model_name='review',
            name='flags',
            field=models.ManyToManyField(db_table='v1_reviews_to_flags', related_name='review', to='lstv_api_v1.ContentFlag'),
        ),
        migrations.AlterField(
            model_name='stateprovince',
            name='subscribers',
            field=models.ManyToManyField(db_table='v1_state_provinces_to_subscribers', related_name='state_province_subscribed_to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tagtype',
            name='curated_properties',
            field=models.ManyToManyField(db_table='v1_tag_types_to_curated_props', related_name='tag_types', to='lstv_api_v1.Properties'),
        ),
        migrations.AlterField(
            model_name='tagtype',
            name='subscribers',
            field=models.ManyToManyField(db_table='v1_tag_types_to_subscribers', related_name='tag_types_subscribed_to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='ip_addresses',
            field=models.ManyToManyField(db_table='v1_users_to_ip_addresses', related_name='ip_user', to='lstv_api_v1.IPAddress'),
        ),
        migrations.AlterField(
            model_name='user',
            name='properties',
            field=models.ManyToManyField(db_table='v1_users_to_properties', related_name='users', to='lstv_api_v1.Properties'),
        ),
        migrations.AlterField(
            model_name='video',
            name='businesses',
            field=models.ManyToManyField(db_table='v1_videos_to_businesses', related_name='videos', to='lstv_api_v1.VideoBusiness'),
        ),
        migrations.AlterField(
            model_name='video',
            name='properties',
            field=models.ManyToManyField(db_table='v1_videos_to_properties', related_name='videos', to='lstv_api_v1.Properties'),
        ),
        migrations.AlterField(
            model_name='video',
            name='q_and_a',
            field=models.ManyToManyField(db_table='v1_videos_to_questions', related_name='videos', to='lstv_api_v1.Message'),
        ),
        migrations.AlterField(
            model_name='video',
            name='shopping_items',
            field=models.ManyToManyField(db_table='v1_videos_to_shopping_items', related_name='videos', to='lstv_api_v1.ShoppingItem'),
        ),
        migrations.AlterField(
            model_name='video',
            name='songs',
            field=models.ManyToManyField(db_table='v1_videos_to_songs', related_name='videos', to='lstv_api_v1.Song'),
        ),
        migrations.AlterField(
            model_name='video',
            name='vibes',
            field=models.ManyToManyField(db_table='v1_videos_to_vibe_types', related_name='videos', to='lstv_api_v1.TagType'),
        ),
        migrations.AlterModelTable(
            name='aggregationcache',
            table='v1_aggregation_cache',
        ),
        migrations.AlterModelTable(
            name='aggregationcachedata',
            table='v1_aggregation_cache_data',
        ),
        migrations.AlterModelTable(
            name='article',
            table='v1_articles',
        ),
        migrations.AlterModelTable(
            name='articleviewlog',
            table='v1_article_view_log',
        ),
        migrations.AlterModelTable(
            name='brand',
            table='v1_brands',
        ),
        migrations.AlterModelTable(
            name='business',
            table='v1_businesses',
        ),
        migrations.AlterModelTable(
            name='businessgrouptype',
            table='v1_business_grouping_types',
        ),
        migrations.AlterModelTable(
            name='businesslocation',
            table='v1_business_locations',
        ),
        migrations.AlterModelTable(
            name='businessphoto',
            table='v1_business_photos',
        ),
        migrations.AlterModelTable(
            name='businessrolefamilytype',
            table='v1_business_role_family_types',
        ),
        migrations.AlterModelTable(
            name='businessroletype',
            table='v1_business_role_types',
        ),
        migrations.AlterModelTable(
            name='businesssubscriptionlevel',
            table='v1_business_subscription_levels',
        ),
        migrations.AlterModelTable(
            name='businessteammember',
            table='v1_business_team_members',
        ),
        migrations.AlterModelTable(
            name='businessteammemberrolepermissiontype',
            table='v1_business_team_member_role_permission_types',
        ),
        migrations.AlterModelTable(
            name='businessteammemberroletype',
            table='v1_business_team_member_role_types',
        ),
        migrations.AlterModelTable(
            name='businessvenueeventspace',
            table='v1_business_venue_event_spaces',
        ),
        migrations.AlterModelTable(
            name='businessvenuetype',
            table='v1_business_venue_types',
        ),
        migrations.AlterModelTable(
            name='businessvenuetypeinfo',
            table='v1_business_venue_type_info',
        ),
        migrations.AlterModelTable(
            name='businessweightedroletype',
            table='v1_business_to_weighted_role_types',
        ),
        migrations.AlterModelTable(
            name='businessweightedworklocationhistory',
            table='v1_business_weighted_work_location_history',
        ),
        migrations.AlterModelTable(
            name='cardimpressionslog',
            table='v1_card_impression_log',
        ),
        migrations.AlterModelTable(
            name='compositecontentbinding',
            table='v1_composite_content_bindings',
        ),
        migrations.AlterModelTable(
            name='compositecontentbindingitem',
            table='v1_composite_content_biding_items',
        ),
        migrations.AlterModelTable(
            name='compositecontentelement',
            table='v1_composite_content_elements',
        ),
        migrations.AlterModelTable(
            name='contentflag',
            table='v1_content_flags',
        ),
        migrations.AlterModelTable(
            name='contentsearchquery',
            table='v1_content_search_queries',
        ),
        migrations.AlterModelTable(
            name='country',
            table='v1_geo_countries',
        ),
        migrations.AlterModelTable(
            name='county',
            table='v1_geo_counties',
        ),
        migrations.AlterModelTable(
            name='curatedlocation',
            table='v1_curated_locations',
        ),
        migrations.AlterModelTable(
            name='directorytype',
            table='v1_directory_types',
        ),
        migrations.AlterModelTable(
            name='discover',
            table='v1_discover',
        ),
        migrations.AlterModelTable(
            name='emailverificationrecord',
            table='v1_email_verification_records',
        ),
        migrations.AlterModelTable(
            name='image',
            table='v1_images',
        ),
        migrations.AlterModelTable(
            name='interviewpagetype',
            table='v1_interview_page_types',
        ),
        migrations.AlterModelTable(
            name='interviewpropertytype',
            table='v1_interview_property_types',
        ),
        migrations.AlterModelTable(
            name='interviewtype',
            table='v1_interview_types',
        ),
        migrations.AlterModelTable(
            name='ipaddress',
            table='v1_ip_to_location',
        ),
        migrations.AlterModelTable(
            name='legacyviewslog',
            table='v1_legacy_views_log',
        ),
        migrations.AlterModelTable(
            name='like',
            table='v1_likes',
        ),
        migrations.AlterModelTable(
            name='location',
            table='v1_locations',
        ),
        migrations.AlterModelTable(
            name='message',
            table='v1_messages',
        ),
        migrations.AlterModelTable(
            name='navigationbarcontent',
            table='v1_navbar_content',
        ),
        migrations.AlterModelTable(
            name='organizedevent',
            table='v1_organized_events',
        ),
        migrations.AlterModelTable(
            name='phone',
            table='v1_phones',
        ),
        migrations.AlterModelTable(
            name='photo',
            table='v1_photos',
        ),
        migrations.AlterModelTable(
            name='place',
            table='v1_geo_places',
        ),
        migrations.AlterModelTable(
            name='placealtname',
            table='v1_geo_place_alt_names',
        ),
        migrations.AlterModelTable(
            name='post',
            table='v1_posts',
        ),
        migrations.AlterModelTable(
            name='promovideo',
            table='v1_promo_videos',
        ),
        migrations.AlterModelTable(
            name='promovideoviewlog',
            table='v1_promo_video_view_log',
        ),
        migrations.AlterModelTable(
            name='properties',
            table='v1_properties',
        ),
        migrations.AlterModelTable(
            name='publicteamperson',
            table='v1_public_business_team_people',
        ),
        migrations.AlterModelTable(
            name='requestlog',
            table='v1_request_log',
        ),
        migrations.AlterModelTable(
            name='resourceorder',
            table='v1_resource_ordering',
        ),
        migrations.AlterModelTable(
            name='review',
            table='v1_reviews',
        ),
        migrations.AlterModelTable(
            name='setting',
            table='v1_settings',
        ),
        migrations.AlterModelTable(
            name='shoppingitem',
            table='v1_shopping_items',
        ),
        migrations.AlterModelTable(
            name='sociallink',
            table='v1_social_links',
        ),
        migrations.AlterModelTable(
            name='socialnetworktypes',
            table='v1_social_network_types',
        ),
        migrations.AlterModelTable(
            name='song',
            table='v1_songs',
        ),
        migrations.AlterModelTable(
            name='songperformer',
            table='v1_song_performers',
        ),
        migrations.AlterModelTable(
            name='stateprovince',
            table='v1_geo_states_provinces',
        ),
        migrations.AlterModelTable(
            name='tagfamilytype',
            table='v1_tag_family_types',
        ),
        migrations.AlterModelTable(
            name='tagtype',
            table='v1_tag_types',
        ),
        migrations.AlterModelTable(
            name='user',
            table='v1_users',
        ),
        migrations.AlterModelTable(
            name='usereventlog',
            table='v1_user_events_log',
        ),
        migrations.AlterModelTable(
            name='video',
            table='v1_videos',
        ),
        migrations.AlterModelTable(
            name='videobusiness',
            table='v1_video_business',
        ),
        migrations.AlterModelTable(
            name='videobusinesscapacitytype',
            table='v1_video_business_capacity_types',
        ),
        migrations.AlterModelTable(
            name='videophoto',
            table='v1_videos_to_photos',
        ),
        migrations.AlterModelTable(
            name='videoplaybacklog',
            table='v1_video_playback_log',
        ),
        migrations.AlterModelTable(
            name='videosource',
            table='v1_video_sources',
        ),
        migrations.AlterModelTable(
            name='videotype',
            table='v1_video_types',
        ),
        migrations.AlterModelTable(
            name='videovideo',
            table='v1_videos_to_video_sources',
        ),
        migrations.AlterModelTable(
            name='videoviewlog',
            table='v1_video_view_log',
        ),
        migrations.AlterModelTable(
            name='weightedworkswith',
            table='v1_weighted_works_with',
        ),
    ]
