# Generated by Django 3.1 on 2021-05-17 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lstv_api_v1', '0136_auto_20210517_1645'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='fileuploadmodel',
            table='v1_file_upload_model',
        ),
    ]
