# Generated by Django 3.1 on 2021-05-18 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lstv_api_v1', '0135_article_content_md'),
        ('lstv_api_v1', '0137_auto_20210517_1651'),
    ]

    operations = [
    ]
