# Generated by Django 3.1 on 2021-05-21 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lstv_api_v1', '0138_merge_20210518_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='website',
            field=models.CharField(db_index=True, max_length=250, null=True),
        ),
    ]
