# Generated by Django 3.1 on 2021-05-21 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lstv_api_v1', '0139_auto_20210521_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='alt_contact_cta_link',
            field=models.CharField(db_index=True, max_length=250, null=True),
        ),
    ]
