# Generated by Django 3.1 on 2021-05-24 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lstv_api_v1', '0140_auto_20210521_2319'),
        ('lstv_api_v1', '0140_auto_20210521_2341'),
    ]

    operations = [
    ]
