datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      url: http://prometheus-server.prometheus.svc.cluster.local
      access: proxy
      isDefault: true

plugins:
  - briangann-gauge-panel
  - grafana-clock-panel
  - grafana-piechart-panel
  - petrslavotinek-carpetplot-panel
  - redis-datasource
  -